import type {
  Notebook,
  Cell,
  PromptCell,
  MarkdownCell,
  VisualizationCell,
  CellOutput,
  TextOutput,
  ToolUseOutput,
  ErrorOutput,
  ChartOutput,
  ThinkingOutput,
  Annotation,
  SlideSection,
  ExportOptions,
} from '@notebook-ai/shared';

// ── HTML escaping ─────────────────────────────────────────────────────────────

function escapeHtml(str: string): string {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

// ── Git diff renderer ─────────────────────────────────────────────────────────

function renderGitDiff(diff: string): string {
  const lines = diff.split('\n');
  const rendered = lines.map((line) => {
    const esc = escapeHtml(line);
    if (line.startsWith('+') && !line.startsWith('+++')) {
      return `<span class="diff-added">${esc}</span>`;
    }
    if (line.startsWith('-') && !line.startsWith('---')) {
      return `<span class="diff-removed">${esc}</span>`;
    }
    if (line.startsWith('@@')) {
      return `<span class="diff-hunk">${esc}</span>`;
    }
    if (line.startsWith('diff ') || line.startsWith('index ') || line.startsWith('---') || line.startsWith('+++')) {
      return `<span class="diff-meta">${esc}</span>`;
    }
    return `<span class="diff-context">${esc}</span>`;
  });
  return rendered.join('\n');
}

// ── Output renderers ──────────────────────────────────────────────────────────

function renderTextOutput(output: TextOutput): string {
  return `<pre class="output-text">${escapeHtml(output.content)}</pre>`;
}

function renderToolUseOutput(output: ToolUseOutput): string {
  const inputJson = JSON.stringify(output.input, null, 2);
  const resultSection = output.result !== undefined
    ? `<div class="tool-result"><strong>Result:</strong><pre>${escapeHtml(output.result)}</pre></div>`
    : '';
  return `
<details class="output-tool-use">
  <summary><span class="tool-badge">tool_use</span> <code>${escapeHtml(output.name)}</code></summary>
  <div class="tool-body">
    <div class="tool-input"><strong>Input:</strong><pre>${escapeHtml(inputJson)}</pre></div>
    ${resultSection}
  </div>
</details>`.trim();
}

function renderErrorOutput(output: ErrorOutput): string {
  return `<div class="output-error"><strong>Error:</strong> <pre>${escapeHtml(output.message)}</pre></div>`;
}

function renderChartOutput(output: ChartOutput): string {
  if (output.svg) {
    // SVG is trusted content generated by the server, but we still wrap it safely
    return `<div class="output-chart">${output.svg}</div>`;
  }
  const dataJson = JSON.stringify(output.data, null, 2);
  return `
<details class="output-chart-data">
  <summary><span class="tool-badge">chart</span> ${escapeHtml(output.chart_type)}</summary>
  <pre>${escapeHtml(dataJson)}</pre>
</details>`.trim();
}

function renderThinkingOutput(output: ThinkingOutput): string {
  return `
<details class="output-thinking">
  <summary><span class="thinking-badge">thinking</span></summary>
  <pre class="thinking-content">${escapeHtml(output.content)}</pre>
</details>`.trim();
}

function renderOutput(output: CellOutput): string {
  switch (output.type) {
    case 'text':
      return renderTextOutput(output);
    case 'tool_use':
      return renderToolUseOutput(output);
    case 'error':
      return renderErrorOutput(output);
    case 'chart':
      return renderChartOutput(output);
    case 'thinking':
      return renderThinkingOutput(output);
    default: {
      // Exhaustiveness guard
      const _exhaustive: never = output;
      return `<pre class="output-text">${escapeHtml(JSON.stringify(_exhaustive, null, 2))}</pre>`;
    }
  }
}

// ── Annotation renderer ───────────────────────────────────────────────────────

function renderAnnotations(annotations: Annotation[], cellId: string): string {
  const cellAnnotations = annotations.filter((a) => a.target_cell === cellId);
  if (cellAnnotations.length === 0) return '';

  const items = cellAnnotations.map((ann) => {
    switch (ann.type) {
      case 'comment':
        return `
<div class="annotation annotation-comment">
  <span class="annotation-type">comment</span>
  <span class="annotation-author">${escapeHtml(ann.author)}</span>
  <span class="annotation-time">${escapeHtml(ann.timestamp)}</span>
  ${ann.selected_text ? `<blockquote class="annotation-quote">${escapeHtml(ann.selected_text)}</blockquote>` : ''}
  <p class="annotation-body">${escapeHtml(ann.comment)}</p>
  ${ann.transcript ? `<p class="annotation-transcript"><em>Transcript:</em> ${escapeHtml(ann.transcript)}</p>` : ''}
</div>`.trim();
      case 'insert':
        return `
<div class="annotation annotation-insert">
  <span class="annotation-type">insert</span>
  <span class="annotation-author">${escapeHtml(ann.author)}</span>
  <span class="annotation-time">${escapeHtml(ann.timestamp)}</span>
  <pre class="annotation-body">${escapeHtml(ann.content)}</pre>
</div>`.trim();
      case 'delete':
        return `
<div class="annotation annotation-delete">
  <span class="annotation-type">delete</span>
  <span class="annotation-author">${escapeHtml(ann.author)}</span>
  <span class="annotation-time">${escapeHtml(ann.timestamp)}</span>
  <del class="annotation-body">${escapeHtml(ann.selected_text)}</del>
</div>`.trim();
      case 'replace':
        return `
<div class="annotation annotation-replace">
  <span class="annotation-type">replace</span>
  <span class="annotation-author">${escapeHtml(ann.author)}</span>
  <span class="annotation-time">${escapeHtml(ann.timestamp)}</span>
  <del class="annotation-body">${escapeHtml(ann.selected_text)}</del>
  <ins class="annotation-body">${escapeHtml(ann.replacement)}</ins>
</div>`.trim();
      default: {
        const _exhaustive: never = ann;
        return `<div class="annotation">${escapeHtml(JSON.stringify(_exhaustive))}</div>`;
      }
    }
  });

  return `<div class="cell-annotations">${items.join('\n')}</div>`;
}

// ── Cell renderers ────────────────────────────────────────────────────────────

function renderPromptCell(cell: PromptCell, annotations: Annotation[], includeAnnotations: boolean): string {
  const statusClass = `status-${cell.status}`;
  const execCount = cell.execution_count > 0 ? `[${cell.execution_count}]` : '[ ]';

  const outputsHtml = cell.outputs.length > 0
    ? `<div class="cell-outputs">${cell.outputs.map(renderOutput).join('\n')}</div>`
    : '';

  const diffHtml = cell.git_diff
    ? `
<details class="cell-git-diff">
  <summary>Git diff</summary>
  <pre class="diff-block">${renderGitDiff(cell.git_diff)}</pre>
</details>`.trim()
    : '';

  const durationHtml = cell.duration_ms !== undefined
    ? `<span class="cell-duration">${cell.duration_ms}ms</span>`
    : '';

  const annotationsHtml = includeAnnotations
    ? renderAnnotations(annotations, cell.id)
    : '';

  return `
<div class="cell cell-prompt ${statusClass}" data-cell-id="${escapeHtml(cell.id)}">
  <div class="cell-header">
    <span class="cell-exec-count">${escapeHtml(execCount)}</span>
    <span class="cell-type-label">prompt</span>
    ${durationHtml}
    <span class="cell-status-dot" title="${escapeHtml(cell.status)}"></span>
  </div>
  <div class="cell-input">
    <pre class="cell-source">${escapeHtml(cell.source)}</pre>
  </div>
  ${outputsHtml}
  ${diffHtml}
  ${annotationsHtml}
</div>`.trim();
}

function renderMarkdownCell(cell: MarkdownCell, annotations: Annotation[], includeAnnotations: boolean): string {
  const annotationsHtml = includeAnnotations
    ? renderAnnotations(annotations, cell.id)
    : '';

  // Render markdown source as a preformatted block. Full markdown parsing
  // would require an external library; we keep output self-contained.
  return `
<div class="cell cell-markdown" data-cell-id="${escapeHtml(cell.id)}">
  <div class="cell-header">
    <span class="cell-type-label">markdown</span>
  </div>
  <div class="cell-input cell-markdown-source">
    <pre class="cell-source markdown-source">${escapeHtml(cell.source)}</pre>
  </div>
  ${annotationsHtml}
</div>`.trim();
}

function renderVisualizationCell(cell: VisualizationCell, annotations: Annotation[], includeAnnotations: boolean): string {
  const configJson = cell.config ? JSON.stringify(cell.config, null, 2) : '{}';
  const annotationsHtml = includeAnnotations
    ? renderAnnotations(annotations, cell.id)
    : '';

  return `
<div class="cell cell-visualization" data-cell-id="${escapeHtml(cell.id)}">
  <div class="cell-header">
    <span class="cell-type-label">visualization</span>
  </div>
  <div class="cell-input">
    <pre class="cell-source">${escapeHtml(cell.source)}</pre>
  </div>
  <details class="viz-config">
    <summary>Config</summary>
    <pre>${escapeHtml(configJson)}</pre>
  </details>
  ${annotationsHtml}
</div>`.trim();
}

function renderCell(cell: Cell, annotations: Annotation[], includeAnnotations: boolean): string {
  switch (cell.type) {
    case 'prompt':
      return renderPromptCell(cell, annotations, includeAnnotations);
    case 'markdown':
      return renderMarkdownCell(cell, annotations, includeAnnotations);
    case 'visualization':
      return renderVisualizationCell(cell, annotations, includeAnnotations);
    default: {
      const _exhaustive: never = cell;
      return `<div class="cell">${escapeHtml(JSON.stringify(_exhaustive))}</div>`;
    }
  }
}

// ── Slide view renderer ───────────────────────────────────────────────────────

function renderSlideSection(section: SlideSection, index: number): string {
  return `
<div class="slide-section" data-section-id="${escapeHtml(section.id)}" data-order="${section.order}">
  <div class="slide-section-header">
    <span class="slide-section-number">${index + 1}</span>
    <h2 class="slide-section-title">${escapeHtml(section.title)}</h2>
  </div>
  <div class="slide-section-content">
    <pre class="slide-content-text">${escapeHtml(section.content)}</pre>
  </div>
  ${section.cell_refs.length > 0
    ? `<div class="slide-cell-refs"><strong>References:</strong> ${section.cell_refs.map((r) => `<code>${escapeHtml(r)}</code>`).join(', ')}</div>`
    : ''}
</div>`.trim();
}

// ── Inline CSS ────────────────────────────────────────────────────────────────

function buildCss(): string {
  return `
/* ── Reset & base ── */
*, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
html { font-size: 14px; }
body {
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
  background: #f8f8f8;
  color: #1a1a1a;
  line-height: 1.5;
}
pre, code {
  font-family: "SFMono-Regular", Consolas, "Liberation Mono", Menlo, monospace;
  font-size: 0.85rem;
}

/* ── Toolbar ── */
.toolbar {
  display: flex;
  align-items: center;
  background: #1e1e2e;
  color: #cdd6f4;
  padding: 0 16px;
  height: 48px;
  gap: 16px;
  position: sticky;
  top: 0;
  z-index: 100;
  box-shadow: 0 2px 8px rgba(0,0,0,0.4);
}
.toolbar-title {
  font-size: 1rem;
  font-weight: 600;
  color: #cba6f7;
  flex: 1;
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
}
.toolbar-meta {
  font-size: 0.75rem;
  color: #6c7086;
}

/* ── Tab bar ── */
.tab-bar {
  display: flex;
  background: #181825;
  border-bottom: 2px solid #313244;
  padding: 0 12px;
  position: sticky;
  top: 48px;
  z-index: 99;
}
.tab {
  background: none;
  border: none;
  color: #6c7086;
  cursor: pointer;
  padding: 10px 20px;
  font-size: 0.875rem;
  font-weight: 500;
  border-bottom: 2px solid transparent;
  margin-bottom: -2px;
  transition: color 0.15s, border-color 0.15s;
}
.tab:hover { color: #cdd6f4; }
.tab.active {
  color: #cba6f7;
  border-bottom-color: #cba6f7;
}

/* ── Tab content ── */
.tab-content { display: none; }
.tab-content.active { display: block; }

/* ── Notebook view ── */
#notebook-view {
  max-width: 900px;
  margin: 24px auto;
  padding: 0 16px 64px;
  display: flex;
  flex-direction: column;
  gap: 16px;
}

/* ── Cells ── */
.cell {
  background: #fff;
  border: 1px solid #e0e0e0;
  border-radius: 6px;
  overflow: hidden;
  box-shadow: 0 1px 3px rgba(0,0,0,0.06);
}
.cell-header {
  display: flex;
  align-items: center;
  gap: 8px;
  padding: 6px 12px;
  background: #f5f5f5;
  border-bottom: 1px solid #e0e0e0;
  font-size: 0.75rem;
  color: #555;
}
.cell-exec-count {
  font-family: monospace;
  color: #888;
  min-width: 28px;
}
.cell-type-label {
  font-size: 0.7rem;
  font-weight: 600;
  text-transform: uppercase;
  letter-spacing: 0.05em;
  padding: 1px 6px;
  border-radius: 3px;
  background: #e8e8e8;
  color: #444;
}
.cell-duration {
  margin-left: auto;
  color: #888;
  font-size: 0.7rem;
}
.cell-status-dot {
  width: 8px;
  height: 8px;
  border-radius: 50%;
  background: #ccc;
  flex-shrink: 0;
}
.status-idle .cell-status-dot { background: #ccc; }
.status-running .cell-status-dot { background: #f5a623; }
.status-completed .cell-status-dot { background: #4caf50; }
.status-error .cell-status-dot { background: #f44336; }

/* Cell borders by status */
.status-running { border-left: 3px solid #f5a623; }
.status-completed { border-left: 3px solid #4caf50; }
.status-error { border-left: 3px solid #f44336; }

.cell-input { padding: 12px; }
.cell-source {
  white-space: pre-wrap;
  word-break: break-word;
  line-height: 1.6;
  color: #1a1a1a;
}
.markdown-source { color: #333; }

/* ── Outputs ── */
.cell-outputs {
  border-top: 1px solid #e8e8e8;
  padding: 12px;
  display: flex;
  flex-direction: column;
  gap: 8px;
}
.output-text {
  background: #fafafa;
  border: 1px solid #e4e4e4;
  border-radius: 4px;
  padding: 10px 12px;
  white-space: pre-wrap;
  word-break: break-word;
  color: #333;
  margin: 0;
}
.output-error {
  background: #fff5f5;
  border: 1px solid #fca5a5;
  border-radius: 4px;
  padding: 10px 12px;
  color: #dc2626;
}
.output-error pre {
  white-space: pre-wrap;
  word-break: break-word;
  margin-top: 4px;
  color: #b91c1c;
}
.output-thinking {
  border: 1px solid #e9d5ff;
  border-radius: 4px;
  background: #faf5ff;
}
.output-thinking summary {
  padding: 8px 12px;
  cursor: pointer;
  list-style: none;
  display: flex;
  align-items: center;
  gap: 6px;
  font-size: 0.8rem;
  color: #7c3aed;
  user-select: none;
}
.output-thinking summary::-webkit-details-marker { display: none; }
.output-thinking .thinking-content {
  padding: 10px 12px;
  white-space: pre-wrap;
  word-break: break-word;
  color: #5b21b6;
  border-top: 1px solid #e9d5ff;
  font-style: italic;
}
.output-tool-use {
  border: 1px solid #d1fae5;
  border-radius: 4px;
  background: #f0fdf4;
}
.output-tool-use summary {
  padding: 8px 12px;
  cursor: pointer;
  list-style: none;
  display: flex;
  align-items: center;
  gap: 6px;
  font-size: 0.8rem;
  color: #065f46;
  user-select: none;
}
.output-tool-use summary::-webkit-details-marker { display: none; }
.tool-body {
  padding: 10px 12px;
  border-top: 1px solid #d1fae5;
  display: flex;
  flex-direction: column;
  gap: 8px;
}
.tool-input pre, .tool-result pre {
  background: #fff;
  border: 1px solid #d1fae5;
  border-radius: 3px;
  padding: 8px;
  white-space: pre-wrap;
  word-break: break-word;
  margin-top: 4px;
  font-size: 0.8rem;
}
.output-chart, .output-chart-data {
  border: 1px solid #dbeafe;
  border-radius: 4px;
  background: #eff6ff;
  padding: 8px;
}
.output-chart svg { max-width: 100%; height: auto; }
.output-chart-data summary {
  padding: 4px;
  cursor: pointer;
  list-style: none;
  user-select: none;
}
.output-chart-data summary::-webkit-details-marker { display: none; }

/* Badges */
.tool-badge {
  display: inline-block;
  padding: 1px 6px;
  border-radius: 3px;
  font-size: 0.68rem;
  font-weight: 700;
  text-transform: uppercase;
  background: #065f46;
  color: #d1fae5;
}
.thinking-badge {
  display: inline-block;
  padding: 1px 6px;
  border-radius: 3px;
  font-size: 0.68rem;
  font-weight: 700;
  text-transform: uppercase;
  background: #7c3aed;
  color: #ede9fe;
}

/* ── Git diff ── */
.cell-git-diff {
  border-top: 1px solid #e8e8e8;
  background: #fafafa;
}
.cell-git-diff summary {
  padding: 6px 12px;
  cursor: pointer;
  list-style: none;
  font-size: 0.8rem;
  color: #555;
  user-select: none;
}
.cell-git-diff summary::-webkit-details-marker { display: none; }
.diff-block {
  padding: 10px 12px;
  white-space: pre;
  overflow-x: auto;
  font-size: 0.8rem;
  border-top: 1px solid #e8e8e8;
  background: #1e1e2e;
  color: #cdd6f4;
  line-height: 1.5;
  margin: 0;
}
.diff-added { color: #a6e3a1; display: block; background: rgba(166,227,161,0.1); }
.diff-removed { color: #f38ba8; display: block; background: rgba(243,139,168,0.1); }
.diff-hunk { color: #89dceb; display: block; }
.diff-meta { color: #6c7086; display: block; }
.diff-context { color: #cdd6f4; display: block; }

/* ── Annotations ── */
.cell-annotations {
  border-top: 1px solid #e8e8e8;
  padding: 10px 12px;
  display: flex;
  flex-direction: column;
  gap: 8px;
  background: #fffbeb;
}
.annotation {
  border-radius: 4px;
  padding: 8px 10px;
  font-size: 0.8rem;
  border-left: 3px solid #d97706;
  background: #fff;
}
.annotation-comment { border-left-color: #3b82f6; }
.annotation-insert { border-left-color: #22c55e; }
.annotation-delete { border-left-color: #ef4444; }
.annotation-replace { border-left-color: #a855f7; }
.annotation-type {
  font-size: 0.65rem;
  font-weight: 700;
  text-transform: uppercase;
  padding: 1px 5px;
  border-radius: 3px;
  background: #e5e7eb;
  color: #374151;
  margin-right: 6px;
}
.annotation-author { font-weight: 600; color: #374151; margin-right: 6px; }
.annotation-time { color: #9ca3af; font-size: 0.7rem; }
.annotation-quote {
  border-left: 2px solid #d1d5db;
  margin: 6px 0;
  padding-left: 8px;
  color: #6b7280;
  font-style: italic;
}
.annotation-body { margin-top: 4px; }
.annotation-transcript { margin-top: 4px; color: #6b7280; }
del { color: #ef4444; }
ins { color: #22c55e; text-decoration: none; }

/* ── Slide view ── */
#slide-view {
  max-width: 900px;
  margin: 24px auto;
  padding: 0 16px 64px;
}
.slide-empty {
  text-align: center;
  color: #9ca3af;
  margin-top: 64px;
  font-size: 1rem;
}
.slide-sections {
  display: flex;
  flex-direction: column;
  gap: 24px;
}
.slide-section {
  background: #fff;
  border: 1px solid #e0e0e0;
  border-radius: 8px;
  overflow: hidden;
  box-shadow: 0 1px 3px rgba(0,0,0,0.06);
}
.slide-section-header {
  display: flex;
  align-items: center;
  gap: 12px;
  padding: 14px 20px;
  background: #1e1e2e;
  color: #cdd6f4;
}
.slide-section-number {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  width: 28px;
  height: 28px;
  border-radius: 50%;
  background: #cba6f7;
  color: #1e1e2e;
  font-weight: 700;
  font-size: 0.85rem;
  flex-shrink: 0;
}
.slide-section-title {
  font-size: 1rem;
  font-weight: 600;
  color: #cdd6f4;
}
.slide-section-content {
  padding: 16px 20px;
}
.slide-content-text {
  white-space: pre-wrap;
  word-break: break-word;
  color: #374151;
  line-height: 1.7;
  font-family: inherit;
  font-size: 0.9rem;
}
.slide-cell-refs {
  padding: 8px 20px 14px;
  color: #9ca3af;
  font-size: 0.75rem;
  border-top: 1px solid #f3f4f6;
}

/* ── Replay panel ── */
.replay-panel {
  position: fixed;
  bottom: 0;
  left: 0;
  right: 0;
  background: #1e1e2e;
  color: #cdd6f4;
  padding: 10px 20px;
  display: flex;
  align-items: center;
  gap: 12px;
  z-index: 200;
  box-shadow: 0 -2px 12px rgba(0,0,0,0.3);
  font-size: 0.85rem;
}
.replay-panel input[type="text"] {
  flex: 1;
  max-width: 360px;
  background: #313244;
  border: 1px solid #45475a;
  border-radius: 4px;
  padding: 6px 10px;
  color: #cdd6f4;
  font-size: 0.85rem;
  outline: none;
}
.replay-panel input[type="text"]:focus {
  border-color: #cba6f7;
}
.replay-btn {
  background: #cba6f7;
  color: #1e1e2e;
  border: none;
  border-radius: 4px;
  padding: 7px 16px;
  font-weight: 700;
  font-size: 0.85rem;
  cursor: pointer;
  transition: background 0.15s;
}
.replay-btn:hover { background: #b4befe; }
.replay-btn:disabled { background: #45475a; color: #6c7086; cursor: not-allowed; }
.replay-status {
  color: #a6e3a1;
  font-size: 0.8rem;
  min-width: 200px;
}
.replay-progress {
  font-size: 0.75rem;
  color: #89b4fa;
}

/* ── Print ── */
@media print {
  .toolbar, .tab-bar, .replay-panel { display: none !important; }
  .tab-content { display: block !important; }
  #slide-view { page-break-before: always; }
  .cell { break-inside: avoid; }
}
`.trim();
}

// ── Inline JS ─────────────────────────────────────────────────────────────────

function buildJs(includeReplay: boolean): string {
  const tabSwitchingJs = `
// ── Tab switching ──
(function () {
  var tabs = document.querySelectorAll('.tab');
  var contents = document.querySelectorAll('.tab-content');

  tabs.forEach(function (tab) {
    tab.addEventListener('click', function () {
      var target = tab.getAttribute('data-target');

      tabs.forEach(function (t) { t.classList.remove('active'); });
      contents.forEach(function (c) { c.classList.remove('active'); c.style.display = 'none'; });

      tab.classList.add('active');
      var el = document.getElementById(target + '-view');
      if (el) { el.classList.add('active'); el.style.display = ''; }
    });
  });
})();
`.trim();

  if (!includeReplay) {
    return tabSwitchingJs;
  }

  const replayJs = `

// ── Replay engine ──
(function () {
  var panel = document.getElementById('replay-panel');
  var urlInput = document.getElementById('replay-url');
  var btn = document.getElementById('replay-btn');
  var statusEl = document.getElementById('replay-status');
  var progressEl = document.getElementById('replay-progress');
  if (!panel || !urlInput || !btn || !statusEl || !progressEl) return;

  panel.style.display = 'flex';

  var notebookDataEl = document.getElementById('notebook-data');
  var notebook = null;
  try { notebook = JSON.parse(notebookDataEl ? notebookDataEl.textContent || '{}' : '{}'); } catch (e) { notebook = null; }

  function setStatus(msg, color) {
    statusEl.textContent = msg;
    statusEl.style.color = color || '#a6e3a1';
  }
  function setProgress(msg) { progressEl.textContent = msg; }

  function clearCellOutputs() {
    document.querySelectorAll('.cell-prompt .cell-outputs').forEach(function (el) {
      el.innerHTML = '';
    });
  }

  function appendOutput(cellId, outputHtml) {
    var cellEl = document.querySelector('.cell-prompt[data-cell-id="' + CSS.escape(cellId) + '"]');
    if (!cellEl) return;
    var outputs = cellEl.querySelector('.cell-outputs');
    if (!outputs) {
      outputs = document.createElement('div');
      outputs.className = 'cell-outputs';
      var input = cellEl.querySelector('.cell-input');
      if (input) { input.parentNode && input.parentNode.insertBefore(outputs, input.nextSibling); }
      else { cellEl.appendChild(outputs); }
    }
    var wrapper = document.createElement('div');
    wrapper.innerHTML = outputHtml;
    while (wrapper.firstChild) { outputs.appendChild(wrapper.firstChild); }
  }

  function setCellStatus(cellId, status) {
    var cellEl = document.querySelector('.cell-prompt[data-cell-id="' + CSS.escape(cellId) + '"]');
    if (!cellEl) return;
    ['status-idle','status-running','status-completed','status-error'].forEach(function (c) { cellEl.classList.remove(c); });
    cellEl.classList.add('status-' + status);
    var dot = cellEl.querySelector('.cell-status-dot');
    if (dot) dot.title = status;
  }

  function renderOutputHtml(output) {
    if (!output || !output.type) return '<pre class="output-text">' + escapeHtml(JSON.stringify(output)) + '</pre>';
    switch (output.type) {
      case 'text':
        return '<pre class="output-text">' + escapeHtml(output.content || '') + '</pre>';
      case 'error':
        return '<div class="output-error"><strong>Error:</strong><pre>' + escapeHtml(output.message || '') + '</pre></div>';
      case 'thinking':
        return '<details class="output-thinking"><summary><span class="thinking-badge">thinking</span></summary><pre class="thinking-content">' + escapeHtml(output.content || '') + '</pre></details>';
      case 'tool_use':
        var inputJson = '';
        try { inputJson = JSON.stringify(output.input || {}, null, 2); } catch(e) { inputJson = '{}'; }
        var resultSection = output.result !== undefined
          ? '<div class="tool-result"><strong>Result:</strong><pre>' + escapeHtml(output.result) + '</pre></div>'
          : '';
        return '<details class="output-tool-use"><summary><span class="tool-badge">tool_use</span> <code>' + escapeHtml(output.name || '') + '</code></summary><div class="tool-body"><div class="tool-input"><strong>Input:</strong><pre>' + escapeHtml(inputJson) + '</pre></div>' + resultSection + '</div></details>';
      default:
        return '<pre class="output-text">' + escapeHtml(JSON.stringify(output)) + '</pre>';
    }
  }

  function escapeHtml(str) {
    return String(str)
      .replace(/&/g, '&amp;')
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;')
      .replace(/"/g, '&quot;')
      .replace(/'/g, '&#39;');
  }

  btn.addEventListener('click', function () {
    if (!notebook) { setStatus('No notebook data found.', '#f38ba8'); return; }
    var promptCells = (notebook.cells || []).filter(function (c) { return c.type === 'prompt'; });
    if (promptCells.length === 0) { setStatus('No prompt cells to replay.', '#f5a623'); return; }

    var serverUrl = (urlInput.value || '').trim();
    if (!serverUrl) { setStatus('Enter a server WebSocket URL.', '#f38ba8'); return; }

    btn.disabled = true;
    clearCellOutputs();
    setStatus('Connecting...', '#89b4fa');

    var ws;
    try {
      ws = new WebSocket(serverUrl);
    } catch (e) {
      setStatus('Failed to create WebSocket: ' + e.message, '#f38ba8');
      btn.disabled = false;
      return;
    }

    var cellQueue = promptCells.slice();
    var currentIdx = 0;
    var completed = false;

    function sendNext() {
      if (currentIdx >= cellQueue.length) {
        setStatus('Replay complete (' + cellQueue.length + ' cells).', '#a6e3a1');
        setProgress('');
        btn.disabled = false;
        completed = true;
        ws.close();
        return;
      }
      var cell = cellQueue[currentIdx];
      setCellStatus(cell.id, 'running');
      setProgress('Cell ' + (currentIdx + 1) + ' / ' + cellQueue.length);
      ws.send(JSON.stringify({ type: 'execute_request', cell_id: cell.id, source: cell.source }));
    }

    ws.onopen = function () {
      setStatus('Connected. Replaying...', '#a6e3a1');
      sendNext();
    };

    ws.onmessage = function (event) {
      var msg;
      try { msg = JSON.parse(event.data); } catch (e) { return; }

      if (msg.type === 'cell_output') {
        appendOutput(msg.cell_id, renderOutputHtml(msg.output));
      } else if (msg.type === 'execution_complete') {
        setCellStatus(msg.cell_id, 'completed');
        currentIdx++;
        sendNext();
      } else if (msg.type === 'error') {
        if (msg.cell_id) {
          setCellStatus(msg.cell_id, 'error');
          appendOutput(msg.cell_id, '<div class="output-error"><strong>Error:</strong><pre>' + escapeHtml(msg.message || '') + '</pre></div>');
          currentIdx++;
          sendNext();
        } else {
          setStatus('Server error: ' + (msg.message || 'unknown'), '#f38ba8');
          btn.disabled = false;
        }
      }
    };

    ws.onerror = function () {
      setStatus('WebSocket error.', '#f38ba8');
      if (!completed) { btn.disabled = false; }
    };

    ws.onclose = function () {
      if (!completed) {
        setStatus('Connection closed unexpectedly.', '#f38ba8');
        btn.disabled = false;
      }
    };
  });
})();
`.trim();

  return tabSwitchingJs + '\n\n' + replayJs;
}

// ── Export: folder-based bundle ───────────────────────────────────────────────
//
// Produces a directory structure:
//   <name>/
//   ├── index.html          (structure, references ./styles.css & ./app.js)
//   ├── styles.css          (all CSS)
//   ├── app.js              (tab switching + replay engine)
//   └── data/
//       └── notebook.json   (full notebook data)
//
// The caller zips this directory for download.  Opening index.html locally
// (file:// protocol) works because everything uses relative paths and no
// external fetches are required (notebook.json is loaded synchronously via
// an inline <script> tag that reads it with a fetch to ./data/notebook.json,
// with a fallback embedded in a <script type="application/json"> block).

import { mkdir, writeFile } from 'fs/promises';
import nodePath from 'path';

export interface ExportBundle {
  /** Absolute path to the created directory. */
  dir: string;
  files: string[];
}

function resolveOpts(options?: Partial<ExportOptions>) {
  return {
    include_slide: options?.include_slide ?? true,
    include_replay: options?.include_replay ?? true,
    include_annotations: options?.include_annotations ?? true,
    minify: options?.minify ?? false,
  };
}

/**
 * Legacy single-file export (still used by WS `export_html` handler).
 */
export async function exportToHtml(notebook: Notebook, options?: Partial<ExportOptions>): Promise<string> {
  const opts = resolveOpts(options);
  const { indexHtml } = buildBundle(notebook, opts, 'inline');
  return indexHtml;
}

/**
 * Folder-based export — writes files to `outDir/<slug>/`.
 * Returns the directory path and file list so the caller can zip & serve.
 */
export async function exportToFolder(
  notebook: Notebook,
  outDir: string,
  options?: Partial<ExportOptions>,
): Promise<ExportBundle> {
  const opts = resolveOpts(options);
  const slug = slugify(notebook.metadata.title);
  const dir = nodePath.join(outDir, slug);
  const dataDir = nodePath.join(dir, 'data');

  await mkdir(dataDir, { recursive: true });

  const { indexHtml, css, js } = buildBundle(notebook, opts, 'external');
  const notebookJson = JSON.stringify(notebook, null, 2);

  const files = [
    nodePath.join(dir, 'index.html'),
    nodePath.join(dir, 'styles.css'),
    nodePath.join(dir, 'app.js'),
    nodePath.join(dataDir, 'notebook.json'),
  ];

  await Promise.all([
    writeFile(files[0], indexHtml, 'utf-8'),
    writeFile(files[1], css, 'utf-8'),
    writeFile(files[2], js, 'utf-8'),
    writeFile(files[3], notebookJson, 'utf-8'),
  ]);

  return { dir, files };
}

function slugify(title: string): string {
  return title
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '') || 'notebook';
}

// ── Build helpers ─────────────────────────────────────────────────────────────

function buildBundle(
  notebook: Notebook,
  opts: ReturnType<typeof resolveOpts>,
  mode: 'inline' | 'external',
) {
  const title = escapeHtml(notebook.metadata.title);
  const createdAt = escapeHtml(notebook.metadata.created);
  const updatedAt = notebook.metadata.updated ? escapeHtml(notebook.metadata.updated) : createdAt;

  const cellsHtml = notebook.cells
    .map((cell) => renderCell(cell, notebook.annotations, opts.include_annotations))
    .join('\n\n');

  let slideHtml: string;
  if (opts.include_slide && notebook.slide.generated && notebook.slide.sections.length > 0) {
    const sorted = [...notebook.slide.sections].sort((a, b) => a.order - b.order);
    slideHtml = `<div class="slide-sections">${sorted.map(renderSlideSection).join('\n\n')}</div>`;
  } else if (opts.include_slide) {
    slideHtml = `<p class="slide-empty">No slide sections generated yet.</p>`;
  } else {
    slideHtml = `<p class="slide-empty">Slide view disabled.</p>`;
  }

  const notebookJson = JSON.stringify(notebook);

  const replayPanelHtml = opts.include_replay
    ? `
<div id="replay-panel" class="replay-panel" style="display:none">
  <strong>Replay:</strong>
  <input id="replay-url" type="text" placeholder="ws://localhost:4003/ws?sessionId=..." value="ws://localhost:4003/ws" />
  <button id="replay-btn" class="replay-btn">Run</button>
  <span id="replay-status" class="replay-status">Enter server URL and click Run to replay notebook.</span>
  <span id="replay-progress" class="replay-progress"></span>
</div>`.trim()
    : '';

  const css = buildCss();
  const js = buildJs(opts.include_replay);

  // In 'external' mode: reference separate files; in 'inline' mode: embed everything.
  const headBlock = mode === 'external'
    ? `  <link rel="stylesheet" href="./styles.css">`
    : `  <style>\n${css}\n  </style>`;

  const scriptBlock = mode === 'external'
    ? `<script src="./app.js"></script>`
    : `<script>\n${js}\n</script>`;

  // Notebook data — always embedded as a <script> tag for file:// compat.
  // In external mode we ALSO write notebook.json for programmatic access.
  const dataBlock = `<script id="notebook-data" type="application/json">\n${notebookJson}\n</script>`;

  const indexHtml = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>${title}</title>
${headBlock}
</head>
<body>

<div class="toolbar">
  <span class="toolbar-title">${title}</span>
  <span class="toolbar-meta">Created: ${createdAt} &middot; Updated: ${updatedAt}</span>
</div>

<nav class="tab-bar">
  <button class="tab active" data-target="notebook">Notebook</button>
  ${opts.include_slide ? '<button class="tab" data-target="slide">Slide</button>' : ''}
</nav>

<div id="notebook-view" class="tab-content active">
${cellsHtml || '<p style="text-align:center;color:#9ca3af;margin-top:48px">No cells.</p>'}
</div>

${opts.include_slide ? `<div id="slide-view" class="tab-content" style="display:none">\n${slideHtml}\n</div>` : ''}

${replayPanelHtml}

${dataBlock}

${scriptBlock}

</body>
</html>`;

  return { indexHtml, css, js };
}
