/**
 * Regression tests for annotation baseline-set send tracking.
 *
 * Tests the behavioral contracts introduced by the cli-online-style
 * baseline set approach:
 *
 * 1. editAnnotation generates a NEW id (old id becomes stale)
 * 2. Highlight map re-keys from old id → new id on edit
 * 3. handleSendSingle is guarded: already-sent id → no-op
 * 4. handleSendAll only includes unsent items in payload
 * 5. After loading persisted annotations, all are in baseline (= sent)
 */

import { describe, it, expect } from 'vitest';
import {
  uid,
  collectAnnotationIds,
  filterSendable,
  applyEdit,
} from '../types/fileAnnotations';
import type { FileAnnotation, FileAnnotations } from '../types/fileAnnotations';
import { rekeyHighlight } from '../utils/annotationHighlight';
import type { HighlightsMap } from '../utils/annotationHighlight';

function makeAnn(id: string, overrides?: Partial<FileAnnotation>): FileAnnotation {
  return {
    id,
    type: 'comment',
    file_path: 'test.md',
    absolute_path: '/tmp/test.md',
    selected_text: 'hello',
    content: 'original',
    cursor: 0,
    author: 'user',
    timestamp: new Date().toISOString(),
    updatedAt: Date.now(),
    ...overrides,
  };
}

// ── 1. applyEdit: generates new ID, preserves other fields ──────────

describe('applyEdit — edit annotation with new ID', () => {
  it('returns items with edited annotation having a new ID', () => {
    const items = [makeAnn('a1'), makeAnn('a2'), makeAnn('a3')];
    const result = applyEdit(items, 'a2', 'updated content');
    // a1 and a3 untouched
    expect(result[0].id).toBe('a1');
    expect(result[2].id).toBe('a3');
    // a2 has new id
    expect(result[1].id).not.toBe('a2');
    expect(result[1].content).toBe('updated content');
  });

  it('preserves non-content fields (type, file_path, selected_text, cursor)', () => {
    const items = [makeAnn('a1', { type: 'replace', selected_text: 'foo', cursor: 42 })];
    const result = applyEdit(items, 'a1', 'new text');
    expect(result[0].type).toBe('replace');
    expect(result[0].selected_text).toBe('foo');
    expect(result[0].cursor).toBe(42);
  });

  it('updates updatedAt timestamp', () => {
    const items = [makeAnn('a1', { updatedAt: 1000 })];
    const before = Date.now();
    const result = applyEdit(items, 'a1', 'new');
    expect(result[0].updatedAt).toBeGreaterThanOrEqual(before);
  });

  it('new ID is unique (generated by uid())', () => {
    const items = [makeAnn('a1')];
    const r1 = applyEdit(items, 'a1', 'v1');
    const r2 = applyEdit(items, 'a1', 'v2');
    expect(r1[0].id).not.toBe(r2[0].id);
  });

  it('returns original items unchanged if id not found', () => {
    const items = [makeAnn('a1')];
    const result = applyEdit(items, 'nonexistent', 'text');
    expect(result).toEqual(items);
  });

  it('edited annotation escapes baseline — becomes sendable again', () => {
    const items = [makeAnn('a1')];
    const baseline = new Set(['a1']); // a1 already sent
    expect(filterSendable(items, baseline)).toHaveLength(0);

    const edited = applyEdit(items, 'a1', 'changed');
    expect(filterSendable(edited, baseline)).toHaveLength(1); // new ID not in baseline
  });
});

// ── 2. rekeyHighlight: re-maps highlight entry on edit ──────────────

describe('rekeyHighlight — re-key highlight map entry', () => {
  const RECTS = [{ x: 10, y: 20, width: 100, height: 16 }];
  const HL: HighlightsMap = {
    a1: { rects: RECTS, bottomY: 44, type: 'comment', capturedScale: 1.0 },
    a2: { rects: RECTS, bottomY: 44, type: 'delete', capturedScale: 1.0 },
  };

  it('moves entry from oldId to newId, preserves data', () => {
    const result = rekeyHighlight(HL, 'a1', 'a1_v2');
    expect(result.a1).toBeUndefined();
    expect(result.a1_v2).toBeDefined();
    expect(result.a1_v2.rects).toEqual(RECTS);
    expect(result.a1_v2.type).toBe('comment');
  });

  it('other entries unaffected', () => {
    const result = rekeyHighlight(HL, 'a1', 'a1_v2');
    expect(result.a2).toBeDefined();
    expect(result.a2.type).toBe('delete');
  });

  it('returns same map if oldId not present', () => {
    const result = rekeyHighlight(HL, 'nonexistent', 'new');
    expect(result).toBe(HL); // reference equal — no change
  });
});

// ── 3. Send single guard ────────────────────────────────────────────

describe('send single — baseline guard', () => {
  it('item NOT in baseline → appears in filterSendable', () => {
    const items = [makeAnn('a1')];
    const baseline = new Set<string>();
    expect(filterSendable(items, baseline)).toHaveLength(1);
  });

  it('item IN baseline → excluded from filterSendable', () => {
    const items = [makeAnn('a1')];
    const baseline = new Set(['a1']);
    expect(filterSendable(items, baseline)).toHaveLength(0);
  });

  it('after adding to baseline, same item becomes unsendable', () => {
    const items = [makeAnn('a1')];
    const baseline = new Set<string>();
    expect(filterSendable(items, baseline)).toHaveLength(1);
    baseline.add('a1');
    expect(filterSendable(items, baseline)).toHaveLength(0);
  });
});

// ── 4. Send all — only unsent, then all marked ──────────────────────

describe('send all — only sends unsent, marks all', () => {
  it('mixed baseline: only unsent items in payload', () => {
    const items = [makeAnn('a1'), makeAnn('a2'), makeAnn('a3')];
    const baseline = new Set(['a1']); // a1 already sent

    const sendable = filterSendable(items, baseline);
    expect(sendable.map(a => a.id)).toEqual(['a2', 'a3']);
  });

  it('after send all: baseline = all current IDs → nothing sendable', () => {
    const items = [makeAnn('a1'), makeAnn('a2'), makeAnn('a3')];
    const baseline = collectAnnotationIds(items); // simulate send all
    expect(filterSendable(items, baseline)).toHaveLength(0);
  });
});

// ── 5. Persistence reload: loaded annotations seed baseline ─────────

describe('persistence reload — loaded annotations are in baseline', () => {
  it('all loaded items are treated as sent', () => {
    const loaded = [makeAnn('a1'), makeAnn('a2')];
    const baseline = collectAnnotationIds(loaded); // seeded on load
    expect(filterSendable(loaded, baseline)).toHaveLength(0);
  });

  it('newly created item (not in loaded set) is sendable', () => {
    const loaded = [makeAnn('a1')];
    const baseline = collectAnnotationIds(loaded);
    const withNew = [...loaded, makeAnn('a_new')];
    expect(filterSendable(withNew, baseline)).toHaveLength(1);
    expect(filterSendable(withNew, baseline)[0].id).toBe('a_new');
  });
});
